### ISSUE TITLE
Fixed one error, gave another error

### ISSUE THREAD

**Issue by stijnb1234** [jwerre/node-canvas-lambda#1]
Hello there,

I've added this layer to my canvas, but now I'm getting this error:

```:/home/container$ /usr/local/bin/node /home/container/index.js
internal/modules/cjs/loader.js:717
return process.dlopen(module, path.toNamespacedPath(filename));
Error: Error loading shared library libresolv.so.2: No such file or directory (needed by /home/container/node_modules/canvas/build/Release/librsvg-2.so.2)
at Object.Module._extensions..node (internal/modules/cjs/loader.js:717:18)
at Module.load (internal/modules/cjs/loader.js:598:32)
at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
at Function.Module._load (internal/modules/cjs/loader.js:529:3)
at Module.require (internal/modules/cjs/loader.js:636:17)
at require (internal/modules/cjs/helpers.js:20:18)
at Object.<anonymous> (/home/container/node_modules/canvas/lib/bindings.js:3:18)
at Module._compile (internal/modules/cjs/loader.js:688:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
at Module.load (internal/modules/cjs/loader.js:598:32)
```

How to fix it?

I'm using Ubuntu 16.04 with the latest versions of all the things. Installed canvas with the npm install canvas command and added the files. 

Kind regards,

Stijn

**Comment by andrewaustin** [comment]
This layer is for AWS Lambda which supposedly runs `amzn2-ami-hvm-2.0.20190313-x86_64-gp2amzn2-ami-hvm-2.0.20190313-x86_64-gp2`. If you're compiling on a different linux, I suspect you'll run into issues. I recommend following the instructions on the node-canvas website for installing with Ubuntu. 

If I've misunderstood and you're actually trying to run on Lambda, I'm not having this problem and I only need the three files the layer provides.

**Comment by jwerre** [comment]
@stijnb1234, @andrewaustin is correct. This is specifically for AWS Lambda functions running the latest version of Amazon Linux.
