### ISSUE TITLE
Latest canvas (2.8.0) fails with "canvas.node: cannot open shared object file: No such file or directory"

### ISSUE THREAD

**Issue by maxpeterson** [jwerre/node-canvas-lambda#14]
Thanks for providing this @jwerre it is super useful, but is there any chance you know how to get it working for the latest `canvas` / `chartjs-node-canvas` versions.

After building the layers with the latest canvas (2.8.0) and deploying to AWS I'm getting the following error from Lambda:

```
 {
  "errorType": "Error",
  "errorMessage": "/opt/nodejs/node_modules/canvas/build/Release/canvas.node: cannot open shared object file: No such file or directory",
  "trace": [
    "Error: /opt/nodejs/node_modules/canvas/build/Release/canvas.node: cannot open shared object file: No such file or directory",
    "    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)",
    "    at Module.load (internal/modules/cjs/loader.js:863:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:708:14)",
    "    at Module.require (internal/modules/cjs/loader.js:887:19)",
    "    at require (internal/modules/cjs/helpers.js:74:18)",
    "    at Object.<anonymous> (/opt/nodejs/node_modules/canvas/lib/bindings.js:3:18)",
    "    at Module._compile (internal/modules/cjs/loader.js:999:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)",
    "    at Module.load (internal/modules/cjs/loader.js:863:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:708:14)"
  ]
}
```

I built  the layers using the `build.sh` and when testing I encountered the above error. My simplest test function is:

```
const { createCanvas } = require('canvas')
```  

FYI: I managed to get a lambda function using the prebuilt layers and the old (pre 4.0.0) `chartjs-node-canvas` API (e.g. using CanvasRenderService):

```
const { CanvasRenderService } = require('chartjs-node-canvas');

exports.handler = async (event) => {
    const chartJSNodeCanvas = new CanvasRenderService(800, 600 ); 

    const response = {
        statusCode: 200,
        body: '<img src="' + await chartJSNodeCanvas.renderToDataURL({}) + '" />',
    };
    return response;
};
```

**Comment by maxpeterson** [comment]
Fixed in #15
